apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rmsslw8v6-nodejs
  janus-idp.io/tekton: rmsslw8v6-nodejs
  backstage.io/kubernetes-id: rmsslw8v6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rmsslw8v6-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
